---
params: 
    title: ""
    Pars: "`r list()`"
    plotPars: "`r list()`"
    tabs: "`r TRUE`"
    its: " `r numeric()`"
    nyears: " `r numeric()`"
    proyears: " `r numeric()`"
    date: "`r Sys.Date()`"
title: "`r params$title`"
date: "`r params$date`"
output:
  html_document
---



## Background to status determination  

A large number of proposed methods of estimating stock status have been suggested in the literature that encompass formal stock assessments all the way to approaches that claim to rely on only catch data. A serious problem with the literature is that the comparative performance of these approaches has not be evaluated. It can be argued that fishery system dynamics are sufficiently unique that few general rules might exist regarding which methods of status evaluation are the most reliable - that these are eccentric to the particularities of a specific fishery. 

To address this MERA includes a range of status determination approaches and tests their expected performance given the simulated conditions described by the questionnaire. This simulation testing provides a context for interpreting real status determinations that can be calculated from real fishery data, uploaded in the Options panel of the MERA questionnaire. 
