---
params: 
    title: ""
    Pars: "`r list()`"
    plotPars: "`r list()`"
    tabs: "`r TRUE`"
    its: " `r numeric()`"
    nyears: " `r numeric()`"
    proyears: " `r numeric()`"
    date: "`r Sys.Date()`"
title: "`r params$title`"
date: "`r params$date`"
output:
  html_document
---

***

## Background to Management Performance and Auxilliary Indicators

In situations where an MP has been adopted and used for management, it is possible to develop indicators that can detect whether the real fishery conditions have departed substantially from those that were simulated (and used to select the MP).

Often referred to as 'Exceptional Circumstances' protocols, these compare the posterior predicted data from the operating model with those that have been observed since MP adoption. 

In most MSE settings, quite simple exceptional circumstances protocols are established that compare the posterior predicted probability intervals of operating model indices of abundance with those indices as they are gathered. 

MERA uses a somewhat more advanced multivariate approach in which multiple types of data can be observed and compared with operating model predictions (Carruthers and Hordyk 2018) under a more general umbrella term 'Auxilliary Indicators'.





