---
params: 
    title: ""
    Pars: "`r list()`"
    plotPars: "`r list()`"
    tabs: "`r TRUE`"
    its: " `r numeric()`"
    nyears: " `r numeric()`"
    proyears: " `r numeric()`"
    date: "`r Sys.Date()`"
title: "`r params$title`"
date: "`r params$date`"
output:
  html_document
---



## Overview

Fisheries managers are in need of tools to inform decision making often in the face of imperfect information and high uncertainty. By linking a simple questionnaire to an operating model and sophisticated simulation software, MERA provides managers with an accessible and powerful tool for identifying species at risk, selecting management procedures that can achieve their performance objectives, and calculating stock status. 

MERA is intended to better account for uncertainty in the fishery system, prioritizing robust management options and identifying value in alternative data collection and research programs. By focusing on operational modelling, MERA can provide quantitative outputs that are central to fishery legal frameworks and eco-certification standards, for example probabilistic estimates of stock status relative to reference levels. MERA lessens the reliance on subjective, qualitative scoring systems, increasing transparency and accountability in decision making. 

Furthermore since App is compatible with the R statistical software operating models, management procedures and diagnostics are all customizable allowing for bespoke state-of-the art closed-loop simulation including MSE. 

