---
params: 
    title: ""
    Pars: "`r list()`"
    plotPars: "`r list()`"
    tabs: "`r TRUE`"
    its: " `r numeric()`"
    nyears: " `r numeric()`"
    proyears: " `r numeric()`"
    date: "`r Sys.Date()`"
title: "`r params$title`"
date: "`r params$date`"
output:
  html_document
---

<br />

## Background to MERA 


### The need for informed management

Fisheries management systems typically involve an ongoing cycle of harvest, data collection, data processing, resource assessment, management recommendations and enforcement of management measures (Walters and Martell 2004). Fisheries managers are embedded in these systems and must make critical decisions, many of which are often poorly informed. 

For example, managers must apportion budgets among various species and competing programs such as data-collection, scientific research, resource assessment and enforcement. Managers must select an appropriate time interval for renewing management advice and the correct level of model complexity for assessing a stock. They must also select among many ways to interpret stock assessment outputs in terms of management advice (i.e. a harvest control rule). Additionally managers may be expected to guide their science program in the direction of the most critical uncertainties in the system that are most in need of research. 

Given that it generally involves the use of public money in the stewardship of public resources it is problematic that even in developed fishery management systems, decision making is often ad-hoc, lacking both transparency in the basis for decisions such as those listed above, and a coherent overall strategy (but see IWC, other exceptions in Australian / South African fisheries REFS).

### Options for informing strategic management

There are two options for evaluating competing modes  of management in order to inform management strategy: experimentation and theoretical modelling. Exploited ecological systems are a notoriously challenging subject for theoretical systems modelling. Due to biological, behavioral and ecological complexities (Rouyer et al. 2008, Sugihara et al. 2011), shifting productivity (Vert Pre et al. 2013), changing environmental conditions, unobserved exploitation (Agnew et al. 2009), variable quality of data and many other factors besides, models may be an inadequate representation of the system, failing to capture critical system dynamics and providing unreliable predictions. 

Empirical testing recognizes these difficulties and evaluates alternative management modes applied in practice to the real system. However, for practical reasons the experimental approach is not feasible for most fisheries. Experimental replication is not possible when the subject is a single fish stock existing in a unique ecological setting precluding rigorous and statistically valid empirical evaluation. Even if it were feasible, the statistical power to detect system changes over relevant time horizons may be expected to be low and experimentation expensive, accounting for the costs of additional data collection and lost fishery yields. For such reasons, proposed experimental approaches to fishery management such as adaptive management (Holling 1978, Walters 2002) have not seen widespread adoption despite their empirical advantages (Walters 2007, Westgate et al. 2013). 

The alternative, theoretical testing, relies on the development of representative systems dynamics models (operating models) to evaluate the expected performance of candidate management modes. While operating models can  be used to inform a wide range of management questions, previous applications in fisheries have generally focused on Management Strategy Evaluation (MSE) in which various ways of setting management advice using data (‘management procedures’) are comparatively evaluated (Butterworth and Punt 1999, Punt et al. 2016).

While there have been criticisms of operational modelling (Rochet and Rice 2009, in reference to MSE), the potential advantages of the approach have made it on ongoing priority for developed fishery management systems at various scales for example, US state fisheries (CDFW 2018), federal fisheries in the US (NOAA 2019) and Canada (Kronlund et al. 2013) and for high seas tuna stocks (Anon 2018). Prevailing obstructions to more widespread development and adoption of operating models include relatively high costs (compared with a one-off assessment of the population) and the availability of suitably qualified analysts and data to inform various scenarios for system dynamics. 

### Contemporary approaches for informing fisheries management

In the absence of rigorous operational modelling, fisheries resource management has often relied on subjective, qualitative frameworks for guidance. A large number of such frameworks exist that aim to evaluate biological risks (Productivity Susceptibility Analysis, PSA: Hobday 2007), stock status (Rapfish; Pitcher 1999), select management options (FISHE: EDF 2019) and prioritize management issues (Fletcher 2005). Such systems have been used widely. For example, PSA has been used in the eco-certification of global fish stocks (Seafoodwatch 2016) and satisfied legal requirements for ecosystem-based fishery management (Hobday et al. 2011). 

Since they simply formalize expert judgement into a scoring system that accepts subjective inputs, it is hard to objectively evaluate both the validity of their assumptions and the quality of advice that they provide. When such systems have been codified and subject to theoretical testing their performance was found to be poor (e.g. biological risk assessment using PSA, Hordyk and Carruthers 2018). 

### MERA objectives

The primary objective of the MERA software (Carruthers et al. 2019) was to provide an accessible tool for the construction of operating models enabling fishery managers to make informed strategic decisions at various levels including data collection, species prioritization, MP selection and enforcement. 

A secondary objective was to support an accessible user interface with sophisticated models and statistical libraries to allow for state-of-the-art operational modelling and MSE when required. Thirdly, MERA was designed to be applicable to the widest range of fisheries possible, various in their scientific understanding, data availability, biological, ecological and exploitation characteristics. 

Lastly, MERA had to be customizable and inform diverse user groups including regional fishery management organizations, international development agencies such as the UN Food and Agricultural Organization and seafood certification bodies such as the Marine Stewardship Council 

